version: "3"
services:
        server:
                build: .
                image: heaty566/mono-shopping-store-be:latest
                expose:
                        - 80
                volumes:
                        - ./config:/app/config
        # redis:
        #         image: "redis:alpine"
        #         ports:
        #                 - 6379:6379
