version: "3"
services:
    server:
        build: .
        image: tantruong2303/mono-shopping-store-be:latest
        expose:
            - 4000
        volumes:
            - ./config:/app/config
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
